table Measure
	lineageTag: 059ecee0-b4b5-4f62-99d3-d42f6b1f9ca8

	measure sales: = SUM(factinternetsales[SalesAmount])
		lineageTag: 27be069b-1f54-4184-80a2-d6d661c95487

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Measure = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

