table Measure
	lineageTag: 2f44410e-6fe4-44b2-add2-4e08d84df34b

	measure 'Order Quantity:' =
			
			SUM(factinternetsales[OrderQuantity])
		formatString: #,0
		lineageTag: af925e18-92af-4bc1-8468-3b4c196395ba

	measure 'Sales Amount:' =
			
			SUM(factinternetsales[SalesAmount])
		formatString: #,0.00
		lineageTag: 3da8cfd4-11c5-4bb6-add3-479be7ffbc8e

	column Column
		isHidden
		formatString: 0
		lineageTag: 020d15c5-4863-4ffd-80d1-dec7046cd493
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition Measure = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 9e39fc70ae124f168bd4dad39f09de21

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

