table _Measure
	lineageTag: a9491f23-4fbb-4a71-9531-332ddb926e00

	measure 'Net order value:' = SUM(orders_fact_databricks[NetOrderValue])
		lineageTag: c39df9f2-3c8e-4008-a0dd-16ca8a6850c0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition _Measure = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

