table dim_calendar
	lineageTag: 0dc1cbc2-fe23-4fb9-9a6e-17059b2db0c4

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: cb506821-c224-40c8-a685-37cb26b5e071
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column DayNumberOfWeek
		dataType: int64
		formatString: 0
		lineageTag: 501af1fb-2f53-498b-8f89-6fde044d203c
		summarizeBy: none
		sourceColumn: DayNumberOfWeek

		annotation SummarizationSetBy = Automatic

	column EnglishDayNameOfWeek
		dataType: string
		lineageTag: 52ca0d3c-e4f2-452a-8403-7f41ab1110e9
		summarizeBy: none
		sourceColumn: EnglishDayNameOfWeek

		annotation SummarizationSetBy = Automatic

	column DayNumberOfMonth
		dataType: int64
		formatString: 0
		lineageTag: 864e7180-3f03-4d9f-a63c-6c7a04d865ca
		summarizeBy: none
		sourceColumn: DayNumberOfMonth

		annotation SummarizationSetBy = Automatic

	column DayNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: 9376fc7f-4e3a-47a9-a5eb-f1eaa0cda039
		summarizeBy: none
		sourceColumn: DayNumberOfYear

		annotation SummarizationSetBy = Automatic

	column WeekNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: faec4a49-6f1d-4c7e-b6a1-d4495738ec86
		summarizeBy: none
		sourceColumn: WeekNumberOfYear

		annotation SummarizationSetBy = Automatic

	column EnglishMonthName
		dataType: string
		lineageTag: 5421b3cc-7f1c-4a78-89ac-14037ecfbdb8
		summarizeBy: none
		sourceColumn: EnglishMonthName

		annotation SummarizationSetBy = Automatic

	column MonthNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: d45322c2-ccf2-4c14-9a92-08472fbaaa63
		summarizeBy: none
		sourceColumn: MonthNumberOfYear

		annotation SummarizationSetBy = Automatic

	column CalendarQuarter
		dataType: int64
		formatString: 0
		lineageTag: c596b3a9-e659-4af8-8bed-15c8c5d1871c
		summarizeBy: none
		sourceColumn: CalendarQuarter

		annotation SummarizationSetBy = Automatic

	column CalendarYear
		dataType: int64
		formatString: 0
		lineageTag: 3e6c4935-1bb6-41c9-a38a-39d3a1aed54e
		summarizeBy: none
		sourceColumn: CalendarYear

		annotation SummarizationSetBy = Automatic

	partition dim_calendar = m
		mode: import
		source =
				let
				    Source = Sql.Databases("77oajh3wezeejnmdlu54fth3om-dmv4edvgwhgubprebu6z6x7bom.datawarehouse.fabric.microsoft.com"),
				    Lakehouse_Adventure_Works = Source{[Name="Lakehouse_Adventure_Works"]}[Data],
				    dbo_dimdate = Lakehouse_Adventure_Works{[Schema="dbo",Item="dimdate"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_dimdate,{"DateKey", "DayNumberOfWeek", "EnglishDayNameOfWeek", "DayNumberOfMonth", "DayNumberOfYear", "WeekNumberOfYear", "EnglishMonthName", "MonthNumberOfYear", "CalendarQuarter", "CalendarYear"})
				in
				    #"Removed Other Columns"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

