table factinternetsales
	lineageTag: 208f71a0-6189-4a43-a46a-30c14fbc183b

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: e35f6dd7-4920-4318-b53b-d3a6b4f37506
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		formatString: 0
		lineageTag: 72eca0a3-2050-4cd1-bcd7-66bd5cb5d246
		summarizeBy: none
		sourceColumn: OrderDateKey

		annotation SummarizationSetBy = Automatic

	column DueDateKey
		dataType: int64
		formatString: 0
		lineageTag: b3e645d5-3cb1-4e6e-9d38-b010409c771f
		summarizeBy: count
		sourceColumn: DueDateKey

		annotation SummarizationSetBy = Automatic

	column ShipDateKey
		dataType: int64
		formatString: 0
		lineageTag: 72504b52-47da-4810-a21d-b5a3d33358b3
		summarizeBy: count
		sourceColumn: ShipDateKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: ed116b3b-d33c-4087-834a-0d90c08fbd74
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column PromotionKey
		dataType: int64
		formatString: 0
		lineageTag: cdff2aa8-bc59-4791-a0ce-f940c23bb61a
		summarizeBy: count
		sourceColumn: PromotionKey

		annotation SummarizationSetBy = Automatic

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: 205060cb-dd81-410c-aa8d-d46642498cb4
		summarizeBy: count
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column SalesOrderNumber
		dataType: string
		lineageTag: 2d9c2766-e27b-4610-bb8c-11784243371d
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineNumber
		dataType: int64
		formatString: 0
		lineageTag: 059683f7-3247-4ef7-a5f8-1fee979ddd0b
		summarizeBy: sum
		sourceColumn: SalesOrderLineNumber

		annotation SummarizationSetBy = Automatic

	column RevisionNumber
		dataType: int64
		formatString: 0
		lineageTag: e15bdcb0-8b4b-4911-be9e-d45a354a566a
		summarizeBy: sum
		sourceColumn: RevisionNumber

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: #,0
		lineageTag: 594a6855-2e82-4a63-8c2f-c83dda485406
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: 4235a9cf-9981-42d0-9895-7f5b58f64587
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ExtendedAmount
		dataType: double
		lineageTag: 9ba3d9e4-c510-4bee-a021-6c22237aba89
		summarizeBy: sum
		sourceColumn: ExtendedAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitPriceDiscountPct
		dataType: double
		lineageTag: bf2585de-43bb-4c10-a27b-63dde27bed81
		summarizeBy: sum
		sourceColumn: UnitPriceDiscountPct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DiscountAmount
		dataType: double
		lineageTag: 3c79b132-d952-48fe-aee7-30f9b45a2b2c
		summarizeBy: sum
		sourceColumn: DiscountAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductStandardCost
		dataType: double
		lineageTag: 78cc0677-dab7-4cfd-b79b-9ad95d775a4b
		summarizeBy: sum
		sourceColumn: ProductStandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalProductCost
		dataType: double
		lineageTag: efa232e1-3f9c-4a53-ad71-c1ac8c821bd8
		summarizeBy: sum
		sourceColumn: TotalProductCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesAmount
		dataType: double
		formatString: #,0.00
		lineageTag: 08d1d4b7-0169-461b-900d-a9d69ba9209b
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

	column TaxAmt
		dataType: double
		lineageTag: c277a0f5-cb8b-4f15-8ab7-e956edf175e3
		summarizeBy: sum
		sourceColumn: TaxAmt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Freight
		dataType: double
		lineageTag: b370b131-28b3-4faa-8882-3d22d78da2ac
		summarizeBy: sum
		sourceColumn: Freight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition factinternetsales = m
		mode: import
		source =
				let
				    Source = Sql.Databases("77oajh3wezeejnmdlu54fth3om-dmv4edvgwhgubprebu6z6x7bom.datawarehouse.fabric.microsoft.com"),
				    Lakehouse_Adventure_Works = Source{[Name="Lakehouse_Adventure_Works"]}[Data],
				    dbo_factinternetsales = Lakehouse_Adventure_Works{[Schema="dbo",Item="factinternetsales"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_factinternetsales,{"ProductKey", "OrderDateKey", "DueDateKey", "ShipDateKey", "CustomerKey", "PromotionKey", "CurrencyKey", "SalesOrderNumber", "SalesOrderLineNumber", "RevisionNumber", "OrderQuantity", "UnitPrice", "ExtendedAmount", "UnitPriceDiscountPct", "DiscountAmount", "ProductStandardCost", "TotalProductCost", "SalesAmount", "TaxAmt", "Freight"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

