table _measures
	lineageTag: beaf3d96-236a-4fcf-814a-99009755b82f

	measure 'Order Quantity:' =
			
			SUM(factinternetsales[OrderQuantity])
		formatString: #,0
		lineageTag: 195093c5-a898-4449-807e-f6000f393328

	measure 'Sales Amount:' =
			
			SUM(factinternetsales[SalesAmount])
		formatString: #,0.00
		lineageTag: 52fbb1b6-4913-4b61-bb0b-11e3cd162764

	column Column1
		dataType: string
		lineageTag: 4c80e80e-94d8-41d4-9b04-436a23551bce
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition _measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t])
				in
				    Source

	annotation PBI_ResultType = Table

