table factinternetsales
	lineageTag: 36445c1e-6615-41d7-a413-b1e57b4fa45c

	refreshPolicy
		policyType: basic
		rollingWindowGranularity: year
		rollingWindowPeriods: 20
		incrementalGranularity: year
		incrementalPeriods: 12
		sourceExpression =
			let
			    Source = Sql.Database("77oajh3wezeejnmdlu54fth3om-dmv4edvgwhgubprebu6z6x7bom.datawarehouse.fabric.microsoft.com", "Lakehouse_Adventure_Works"),
			    dbo_factinternetsales = Source{[Schema="dbo",Item="factinternetsales"]}[Data],
			    #"Filtered Rows" = Table.SelectRows(dbo_factinternetsales, each [OrderDateKey] > DateKey(RangeStart) and [OrderDateKey] <= DateKey(RangeEnd))
			in
			    #"Filtered Rows"

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 0f01fb7f-1943-40fa-ad9c-33571a55eb60
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		formatString: 0
		lineageTag: 9b300c4f-6291-4541-9cb8-049e47655674
		summarizeBy: none
		sourceColumn: OrderDateKey

		annotation SummarizationSetBy = Automatic

	column DueDateKey
		dataType: int64
		formatString: 0
		lineageTag: b16a56a3-7516-4dcf-b1df-5df565573197
		summarizeBy: count
		sourceColumn: DueDateKey

		annotation SummarizationSetBy = Automatic

	column ShipDateKey
		dataType: int64
		formatString: 0
		lineageTag: ab5517d7-3acd-4f35-be86-1d9083b971a0
		summarizeBy: count
		sourceColumn: ShipDateKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: d504d951-4c62-47cf-90b0-2d9509c12024
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column PromotionKey
		dataType: int64
		formatString: 0
		lineageTag: acf4fe0a-a4f2-4423-a97c-6d1d167458af
		summarizeBy: count
		sourceColumn: PromotionKey

		annotation SummarizationSetBy = Automatic

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: cdfe6f34-ede0-4db5-837b-ac2e38925852
		summarizeBy: count
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: 586be2d2-8835-457c-9d5a-c5435e7cc07d
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column SalesOrderNumber
		dataType: string
		lineageTag: 1b27f381-7681-4443-a5c1-51267af4f9bd
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineNumber
		dataType: int64
		formatString: 0
		lineageTag: 66ef92fa-6eec-48af-847d-d8b91659772d
		summarizeBy: sum
		sourceColumn: SalesOrderLineNumber

		annotation SummarizationSetBy = Automatic

	column RevisionNumber
		dataType: int64
		formatString: 0
		lineageTag: 5c96149b-832c-4af8-8699-935995107e6a
		summarizeBy: sum
		sourceColumn: RevisionNumber

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: 5b5f7059-4f22-413b-a65e-ddaabac323fb
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: 6a8c8a5c-f4e4-4fab-8aee-1d8080baf37a
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ExtendedAmount
		dataType: double
		lineageTag: f9a7bd0f-d86c-4119-b900-3c6b28520e3f
		summarizeBy: sum
		sourceColumn: ExtendedAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitPriceDiscountPct
		dataType: double
		lineageTag: 6d454776-3099-4ad1-b246-e0d6992d09ae
		summarizeBy: sum
		sourceColumn: UnitPriceDiscountPct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DiscountAmount
		dataType: double
		lineageTag: 4a7a5cfb-3636-465b-b948-c252c5388ca4
		summarizeBy: sum
		sourceColumn: DiscountAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductStandardCost
		dataType: double
		lineageTag: fc92b1a4-dc24-41ac-b66a-f4df28557dc8
		summarizeBy: sum
		sourceColumn: ProductStandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalProductCost
		dataType: double
		lineageTag: f706464c-93b4-488b-a31e-3736b8649e9b
		summarizeBy: sum
		sourceColumn: TotalProductCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesAmount
		dataType: double
		lineageTag: c7eb2b36-71ee-4820-8572-8c255e667b14
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TaxAmt
		dataType: double
		lineageTag: 947238db-9bc1-48b3-9341-60b41d915e89
		summarizeBy: sum
		sourceColumn: TaxAmt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Freight
		dataType: double
		lineageTag: 440999b9-3cdb-4ecf-889e-d43cd648e50e
		summarizeBy: sum
		sourceColumn: Freight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: e3d107d1-3b3a-4527-b249-4fdb52508892
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

	column DueDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 08b89d1e-0bb1-4952-a192-89d7c2759016
		summarizeBy: none
		sourceColumn: DueDate

		annotation SummarizationSetBy = Automatic

	column ShipDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 7f919589-b425-45f0-8286-aa607693b3ce
		summarizeBy: none
		sourceColumn: ShipDate

		annotation SummarizationSetBy = Automatic

	partition factinternetsales = m
		mode: import
		source =
				let
				    Source = Sql.Database("77oajh3wezeejnmdlu54fth3om-dmv4edvgwhgubprebu6z6x7bom.datawarehouse.fabric.microsoft.com", "Lakehouse_Adventure_Works"),
				    dbo_factinternetsales = Source{[Schema="dbo",Item="factinternetsales"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dbo_factinternetsales, each [OrderDateKey] > DateKey(RangeStart) and [OrderDateKey] <= DateKey(RangeEnd))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

